server:
  port: 10010
spring:
  application:
    name: platform-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    platform-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
  add-host-header: true   # 携带请求本身的head头信息
  sensitive-headers:      # 配置禁止使用的头信息，这里设置为null，否则set-cookie无效
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 10000

auth:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub
    cookieName: WACKYBOY

platform:
  filter:
    allowPaths:
      - /api/auth
      - /api/user/register
      - /api/user/check
      - /api/item/talk

headers:
  Access-Control-Expose-Headers: 'Set-Cookie'
